# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c7fce26eb53e03a9270e964b449f6e23ab0fe5322a3266396f165d20f4d78bc0489cf044e7a61e132cb0b30ffdf6a6aaabc5c761b4cf9a07cbd3123bf630700f

test:
  secret_key_base: 3b62b1fdc8ef86c2663f74701e9d7c5a4b8ff56cd32e3566b2e2f537e1442262de984dcf140f9ac92c86e7d73f3b3c6f39e9bb52a54522be9729bd64dbfaa474

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
